config/urls.py
from django.contrib import admin

from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("scheduler.urls")),
]

scheduler/urls.py
from django.urls import path
from . import views

#P31のアプリケーションごとにurls.pyを配置するを参照
app_name    = "scheduler"
urlpatterns = [
    path('', views.index, name="index"),
    path('delete/', views.delete, name="delete"), #←ここに削除用の処理のパスを追加する
    path('edit/', views.edit, name="edit"), #←ここに編集用の処理のパスを追加する
]

scheduler/models.py
from django.db import models

#P46のモデルクラスの書き方を参照
class Scheduler(models.Model):
    class Meta:
        db_table    = "scheduler"

    #DBのカラム(タテ列)に当たるフィールドを指定する(P47を参照)
    deadline    = models.DateTimeField(verbose_name="締め切り日時")
    task        = models.CharField(verbose_name="やること",max_length=500)
    done        = models.BooleanField(default=False)


    #管理サイト閲覧時、1つのレコード(ヨコ列)をprint文で出力時、taskが表示される。
    def __str__(self):
        return self.task

#モデルを定義した後はマイグレーションを実行し、DBに反映させる
"""
python3 manage.py makemigrations
python3 manage.py migrate 
"""

scheduler/forms.py
from django import forms 

from django.forms import ModelForm
from .models import Scheduler


#モデルを継承したフォーム、P91を参照。modelのクラス名を指定。models.pyで定義した検証するフィールド(今回はdeadlineとtask)を指定。
#これにより、指定した文字数をはみ出していないか、入力必須の項目を入力しているか、型が間違っていないかなどを検証できる。
class SchedulerForm(ModelForm):
    class Meta:
        model   = Scheduler
        fields  = [ "deadline","task" ]

#モデルを継承しないで作るフォーム。フォームクラスの書き方P85を参照。
#今回はIDが数値型であることを確認できればいいので属性は未指定
class SchedulerIDForm(forms.Form):
    id  = forms.IntegerField()

scheduler/views.py
from django.shortcuts import render,redirect,get_object_or_404

from django.views import View

#カスタムクエリを使う
from django.db.models import Q

#models.pyで定義したSchedulerをimportする
from .models import Scheduler

from .forms import SchedulerForm,SchedulerIDForm


#P35のビュー関数の書き方(関数ベース vs クラスベース)を参照。後の汎用性も考慮しクラスベースのビューを採用した。
class SchedulerView(View):

    def get(self, request, *args, **kwargs):

            # GET文のリクエストの中に、name属性searchがある場合(検索された時)の処理
        if "search" in request.GET:

                # (1)キーワードが空欄もしくはスペースのみの場合、ページにリダイレクト
                if request.GET["search"] == "" or request.GET["search"].isspace():
                    return redirect("scheduler:index")

                # (2)キーワードをリスト化させる(複数指定の場合に対応させるため)
                search = request.GET["search"].replace("　", " ")
                search_list = search.split(" ")

                # (3)クエリを作る
                query = Q()

                # TODO:ここでANDとORを分岐させる
                for word in search_list:
                    # TIPS:AND検索の場合は&を、OR検索の場合は|を使用する。
                    if "checkbox" in request.GET:
                        if request.GET["checkbox"]:
                            query &= Q(task__contains=word)
                        else:
                            query |= Q(task__contains=word)
                    else:
                        query |= Q(task__contains=word)

                    # (4)作ったクエリを実行
                data = Scheduler.objects.filter(query)

        else:
                # .all()メソッドを使用することでDBに格納されているSchedulerのデータを全て抽出できる(P57)
                # .order_by()メソッドを使い、並び替えをする(P61)
                data = Scheduler.objects.all().order_by("deadline")

        context = {"data": data}

        return render(request, "scheduler/index.html", context)

    def post(self ,request, *args, **kwargs):

        #クライアントから受け取ったデータをDBに格納する。(P62)
        """
        posted  = Scheduler(  deadline    = request.POST["deadline"],
                              task        = request.POST["task"]    )
        posted.save()
        """

        #ここに送信されたデータがSchedulerFormに引数として与えられ、.is_valid()でバリデーションを行う。P87のビューでの利用例を参照
        formset = SchedulerForm(request.POST)
        
        #バリデーションOKの場合、Trueが返ってくる。
        if formset.is_valid():
            #モデルを継承して作ったformsのクラスの場合、.save()メソッドを使うことでDBに保存できる。
            formset.save()
        else:
            print("バリデーションエラー")
        return redirect("scheduler:index")

#クラスで記述したビューを関数化するための処理。これによりurls.pyから呼び出せる
index   = SchedulerView.as_view()


#指定したスケジュールを削除するクラス
class SchedulerDelete(View):

    def post(self ,request, *args, **kwargs):

        #削除対象のレコードをIDで一意に特定する。.delete()で削除
        """
        posted  = Scheduler.objects.filter(id=request.POST["id"])
        posted.delete()
        """

        #バリデーションを行う
        formset = SchedulerIDForm(request.POST)

        #バリデーションが適切であれば削除処理、そうでなければエラー表示
        if formset.is_valid():

            #バリデーションした後の値を取り出す
            clean_data  = formset.clean()

            #filterで絞り込み、.delete()で削除処理をする。
            Scheduler.objects.filter(id=clean_data["id"]).delete()

        else:
            print("バリデーションエラー")
        return redirect("scheduler:index")

delete  = SchedulerDelete.as_view()


#編集処理を行うクラス
class SchedulerEdit(View):

    def post(self ,request, *args, **kwargs):

        formset = SchedulerIDForm(request.POST)

        if formset.is_valid():
            clean_data      = formset.clean()
            target          = clean_data["id"]
        else:
            print("バリデーションNG(IDがありません)")
            return redirect("scheduler:index")
            
        #get_object_or_404は存在するIDであればそのまま次の処理を、存在しなければNotFoundを返す。
        instance    = get_object_or_404(Scheduler.objects.all(), pk=target)

        #第二引数にinstanceを指定することで、対象の編集ができる
        formset     = SchedulerForm(request.POST, instance=instance)

        if formset.is_valid():
            print("バリデーションOK")
            formset.save()
        else:
            print("バリデーションNG")

        return redirect("scheduler:index")

edit    = SchedulerEdit.as_view()

templates/scheduler/index.html
{% load static %}
<!--↑staticディレクトリに格納した静的ファイルを読み込みするときは必ず指定-->


<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
	<title>スケジューラー</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

    <link rel="stylesheet" href="{% static 'scheduler/css/style.css' %}">



    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <!-- staticを使って、JSファイルを読み込みましょう。 
        <script src="script.js"></script> 
        -->

    <!--日本語化用JS-->
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ja.js"></script>
    <script src="{% static 'scheduler/js/script.js' %}"></script>


</head>
<body onload="LoadProc();">
    <h1 class="bg-primary text-center text-white">スケジューラー</h1>

    <main class="containerM">
        <h1 id="RealtimeClockArea2" class="text-center"></h1>
        <form method="POST">
            <!--↓POST文実行時はCSRF対策のため必ず指定-->
            {% csrf_token %}
            <!--POST文を送信した際、name属性を元にviews.pyが参照を行う-->
            <input id="dt" type="text" name="deadline" readonly value="クリックで日時を指定" required>
            <!--
            <input class="form-control" name="deadline" type="datetime-local" value="2020-12-06 11:30:00">
            -->
            <textarea class="form-control" name="task" placeholder="ここにやることを書く＊日時、内容を記入しないと反映されません" rows="3" required maxlength="500"></textarea>
            <input class="form-control" type="submit" value="送信">
        </form>

        <form action="" method="GET">

            <!--ここにチェックボックスを設置すれば、AND検索とOR検索を切り替えられるようにする事ができる。-->
            <div class="row align-items-center mx-0">

                <input class="col-5" type="text" name="search" placeholder="キーワード検索" value="{{ request.GET.search }}">
                <!--↑value属性に指定されている request.GET.search のテンプレート変数を使えば、検索キーワードをそのまま表示できる-->
                <input class="col-1" type="submit" value="{{ ANDOR }}検索">
                    <div class="ui_demo_area col-2">
                        <input id="ios_chk_01" name="checkbox" class="ui20-input_chk" type="checkbox" {% if request.GET.checkbox %}checked{% endif %}><label class="ui20-ios_conf" for="ios_chk_01"></label>
                    </div>
                <div class="col-4"></div>
            </div>
        </form>

        <!--
        <input id="date" type="text" readonly>
        <input id="time" type="text" readonly>

        <input id="dt" type="text" readonly>
        -->

        <!--↓テンプレートタグで繰り返し処理、条件分岐を行うことが可能(P74)-->
        <div class="table-responsive My-table">
            <table class="table">
                <tbody class="border">
                <div>{{ data|length }} 件ヒットしています</div>
                    <thead class="thead-light">
                        <tr><th><div>日時</div></th><th><div>内容</div></th><th style="white-space:nowrap;"><div>削除</div></th><th style="white-space:nowrap;"><div>編集</div></th></tr>
                    </thead>
                    <!--↓テンプレート変数(p70)-->
                    {% for content in data %}
                    <tr><td style="white-space:nowrap;"><div id="{{ content.id }}_deadline">{{ content.deadline|date:"Y年m月d日 H時i分" }}</div></td><td><div id="{{ content.id }}_task">{{ content.task|linebreaksbr }}</div></td>
                        <td style="white-space:nowrap;">
                            <div>
                                <!-- ↓ urls.pyでURLが delete/ と定義したビューにPOST文を送る-->
                                <form action="{% url 'scheduler:delete' %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-outline-danger" name="id" value ="{{ content.id }}">削除</button>
                                </form>

                            </div>
                        </td>
                        <td style="white-space:nowrap;">
                            <div>
                                <button class="btn btn-outline-success edit_button" value="{{ content.id }}">編集</button>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>


        <!--モーダルウィンドウ-->
        <div id="modal">
            <div id="modal_content" class="container">
                <!--ここに編集先のURLを-->
                <form action="{% url 'scheduler:edit' %}" method="POST" class="p-1">

                    {% csrf_token %}

                    <input id="edit_target_id" type="hidden" value="" name="id">
                    
                    <h2 class="text-center">編集中</h2>

                    <input id="modal_deadline" type="text" value="" name="deadline" readonly required>
                    <textarea id="modal_task" class="form-control" rows="6" name="task" required maxlength="500"></textarea>

                    <input class="form-control" type="submit" value="編集">

                </form>
            </div>
        </div>

    </main>



</body>
</html>